name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #checkout repository
      - uses: actions/checkout@v4

      # configuration java sdk version
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      # create Google Services JSON File
      - name: Create Google Services JSON File
        run: cat /home/runner/work/iRecipe/iRecipe/app/google-services.json | base64

      # configuration google services file
      - name: Putting Google Services JSON data
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > /home/runner/work/iRecipe/iRecipe/app/google-services.json

      # configuration api key
      - name: Use API from secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=\"$API_KEY\" > ./local.properties

      # Build with Gradle
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew assembleDebug --no-build-cache --no-configuration-cache

      # Run unit tests
      - name: Run unit tests
        run: chmod +x ./gradlew &&./gradlew testDebugUnitTest

      # Run Klint Check
      - name: Run Klint Check
        run: ./gradlew ktlintCheck

      # Run Detekt
      - name: Run Detekt
        run: ./gradlew detekt
        if: success() || failure()